// priority: 5

onEvent('recipes', event => {
    event.shapeless('minecraft:oak_trapdoor', ['tfc:wood/planks/oak_trapdoor'])
    event.shapeless('minecraft:oak_trapdoor', ['tfc:wood/planks/maple_trapdoor'])
    event.shapeless('minecraft:oak_door', ['tfc:wood/planks/oak_door'])
    event.shapeless('minecraft:oak_door', ['tfc:wood/planks/maple_door'])
    event.shapeless('minecraft:oak_planks', ['tfc:wood/planks/oak'])
    event.shapeless('minecraft:oak_planks', ['tfc:wood/planks/maple'])
//------------------------------------------------------------------------------------
    event.shapeless('minecraft:spruce_trapdoor', ['tfc:wood/planks/sequoia_trapdoor'])
    event.shapeless('minecraft:spruce_trapdoor', ['tfc:wood/planks/spruce_trapdoor'])
    event.shapeless('minecraft:spruce_door', ['tfc:wood/planks/sequoia_door'])
    event.shapeless('minecraft:spruce_door', ['tfc:wood/planks/spruce_door'])
    event.shapeless('minecraft:spruce_planks', ['tfc:wood/planks/sequoia'])
    event.shapeless('minecraft:spruce_planks', ['tfc:wood/planks/spruce'])
//------------------------------------------------------------------------------------
    event.shapeless('minecraft:birch_trapdoor', ['tfc:wood/planks/birch_trapdoor'])
    event.shapeless('minecraft:birch_trapdoor', ['tfc:wood/planks/douglas_fir_trapdoor'])
    event.shapeless('minecraft:birch_trapdoor', ['tfc:wood/planks/pine_trapdoor'])
    event.shapeless('minecraft:birch_door', ['tfc:wood/planks/birch_door'])
    event.shapeless('minecraft:birch_door', ['tfc:wood/planks/douglas_fir_door'])
    event.shapeless('minecraft:birch_door', ['tfc:wood/planks/pine_door'])
    event.shapeless('minecraft:birch_planks', ['tfc:wood/planks/birch'])
    event.shapeless('minecraft:birch_planks', ['tfc:wood/planks/douglas_fir'])
    event.shapeless('minecraft:birch_planks', ['tfc:wood/planks/pine'])
//------------------------------------------------------------------------------------
    event.shapeless('minecraft:jungle_trapdoor', ['tfc:wood/planks/ash_trapdoor'])
    event.shapeless('minecraft:jungle_trapdoor', ['tfc:wood/planks/sycamore_trapdoor'])
    event.shapeless('minecraft:jungle_door', ['tfc:wood/planks/ash_door'])
    event.shapeless('minecraft:jungle_door', ['tfc:wood/planks/sycamore_door'])
    event.shapeless('minecraft:jungle_planks', ['tfc:wood/planks/ash'])
    event.shapeless('minecraft:jungle_planks', ['tfc:wood/planks/sycamore'])
//------------------------------------------------------------------------------------
    event.shapeless('minecraft:acacia_trapdoor', ['tfc:wood/planks/acacia_trapdoor'])
    event.shapeless('minecraft:acacia_trapdoor', ['tfc:wood/planks/rosewood_trapdoor'])
    event.shapeless('minecraft:acacia_door', ['tfc:wood/planks/acacia_door'])
    event.shapeless('minecraft:acacia_door', ['tfc:wood/planks/rosewood_door'])
    event.shapeless('minecraft:acacia_planks', ['tfc:wood/planks/acacia'])
    event.shapeless('minecraft:acacia_planks', ['tfc:wood/planks/rosewood'])
//------------------------------------------------------------------------------------
    event.shapeless('minecraft:dark_oak_trapdoor', ['tfc:wood/planks/aspen_trapdoor'])
    event.shapeless('minecraft:dark_oak_trapdoor', ['tfc:wood/planks/blackwood_trapdoor'])
    event.shapeless('minecraft:dark_oak_trapdoor', ['tfc:wood/planks/hickory_trapdoor'])
    event.shapeless('minecraft:dark_oak_door', ['tfc:wood/planks/aspen_door'])
    event.shapeless('minecraft:dark_oak_door', ['tfc:wood/planks/blackwood_door'])
    event.shapeless('minecraft:dark_oak_door', ['tfc:wood/planks/hickory_door'])
    event.shapeless('minecraft:dark_oak_planks', ['tfc:wood/planks/aspen'])
    event.shapeless('minecraft:dark_oak_planks', ['tfc:wood/planks/blackwood'])
    event.shapeless('minecraft:dark_oak_planks', ['tfc:wood/planks/hickory'])
})